### ISSUE TITLE
FileNotFoundError FFMPEG. Subprocess call outdated?

### ISSUE THREAD

**Issue by JanTi7** [ree1261/pyvidplayer2#1]
#### Description
When trying to play a video using the player, it states the following error:
```
FileNotFoundError: [Errno 2] No such file or directory: '"ffmpeg" -i "example.mp4" -ss 0:0:0.0 -t 0:5:0.0 -f wav -loglevel quiet -'
```

I suspect the subprocess call to be outdated (read below).

#### To Reproduce / The used setup
- running from virtual environment
- on Ubuntu 20.04.5 LTS
- use provided minimal script in README (found at chapter 'Quickstart')
- Python 3.8.10

#### Code Change
Replacing [this line](https://github.com/ree1261/pyvidplayer2/blob/b9a1ea736f65f09c9fe625c2cc4fd0ef538132b8/pyvidplayer2/video.py#L77C9-L77C168) with the following fixed the issue for me. The subprocess.run() command expects a list of strings instead of a single string.
```
p = subprocess.run([get_ffmpeg_path(), '-i', self.path, '-ss', str(s), '-t', str(self._convert_seconds(self.chunk_size)), '-f', 'wav', '-loglevel', 'quiet', '-'], capture_output=True)
```

#### Note
Hope this helps, sorry for any confusion, this is my first Issue ever submitted.

**Comment by ree1261** [comment]
Hello, thanks for this information.

I haven't tested it yet, but I'll release a patch soon. In the meantime, how was your experience with the rest of the library?

**Comment by JanTi7** [comment]
> Hello, thanks for this information.
> 
> I haven't tested it yet, but I'll release a patch soon. In the meantime, how was your experience with the rest of the library?

Quite well, I am not using it for anything special, just playing a simple video in a game, but that works without any issues (after the fix above). Thanks for your work!

**Comment by ree1261** [comment]
It appears I was using the windows way of calling commands. It shouldn't be an issue now with version 0.9.4. Cheers!
