### ISSUE TITLE
Change Video Size

### ISSUE THREAD

**Issue by jjstorm98** [ree1261/pyvidplayer2#7]
Hi im having difficulty figuring out how to adjust the width and height of the video.

**Comment by jjstorm98** [comment]
i figured it out:
# Load the background image
background = pygame.image.load("background1.jpg")
background = pygame.transform.scale(background, (monitor_width, monitor_height))

# Calculate the desired size and position of the video box
video_box_width, video_box_height = int(win.get_width() * 0.77), int(win.get_height() * 0.76)  # Adjust the size as needed

video_box_x = (monitor_width - video_box_width) // 3
video_box_y = (monitor_height - video_box_height) // 2

# Create a separate surface for the video box
video_box = pygame.Surface((video_box_width, video_box_height))  # Adjust the size as needed

# Adjust video size as needed
#video_width, video_height = 640, 360  # Adjust the video size as needed

# Provide video class with the path to your video
vid = Video(r".mp4")
vid.resize((video_box_width, video_box_height))

**Comment by ree1261** [comment]
Good day,

You can also look at the VideoPlayer class. It's designed as a user interface for your videos, but you can turn this part off with the interactable=False argument. By using this class, you get automatic video resizing. Simply pass the class a rectangle and your video will be resized and centered to best utilize the given space. Empty space will be filled with black bars. From there, you can get data on both your allocated space with the frame_rect attribute and video rect with video_rect.

Anyway, glad you figured out your issue.
